### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by kouz1234** [nucleon/wintertodt-scouter#11]
The plugin is currently not pulling any world data and appearing blank for the world, health, and time fields.

![Screenshot_1](https://github.com/nucleon/wintertodt-scouter/assets/112707198/41b36d0a-d6e6-40ca-87c9-5fe1f0794f58)

**Comment by nucleon** [comment]
should be fixed

**Comment by hyroqi** [comment]
still not loading for me, tried uninstalling and reinstalling as well
![image](https://github.com/nucleon/wintertodt-scouter/assets/48770581/b1d9b79d-94e5-432c-a365-41c74aa5d5d6)

**Comment by dansosrs** [comment]
same

**Comment by nucleon** [comment]
alright, i'll look into it now

**Comment by nucleon** [comment]
@dansosrs @kouz1234 I restored the server, looks like the data was corrupt somehow. I logged into RuneLite to check and it's pulling the data now.

**Comment by nucleon** [comment]
![image](https://github.com/nucleon/wintertodt-scouter/assets/4823135/5a91455e-6a95-4749-a917-369852e5e235)

**Comment by hyroqi** [comment]
yep works, thanks nucleon
